### ISSUE TITLE
error when using with redux-bundler-async-resources-hooks

### ISSUE THREAD

**Issue by huygn** [abuinitski/redux-bundler-async-resources#1]
when using `useAsyncResource`, if I didn't provided `dependencyKey` to `createAsyncResourceBundle` it will throw an error saying `select${name}DependencyValues` selector not found. Could we put this [selector](https://github.com/abuinitski/redux-bundler-async-resources/blob/master/src/createAsyncResourceBundle.js#L314) outside the `if` block to avoid above error? imo the selector should be there even if it resolve to `null`.

@abuinitski If you are ok with this, I will put up a PR, cheers.

**Comment by abuinitski** [comment]
@huygn released in 1.2.1
